from docx import Document as DocxDocument
import os
import pandas as pd
class DocxReader:
    '''
    Generated by ChatGPT for reading a docx file
    '''
    def __init__(self, filename):
        self.filename = filename
        self.doc = DocxDocument(filename)

    def get_metadata(self):
        metadata = {}

        # Extract core properties
        core_props = self.doc.core_properties
        metadata["title"] = core_props.title
        metadata["author"] = core_props.author
        metadata["created"] = core_props.created
        metadata["modified"] = core_props.modified

        return metadata

    def get_text(self):
        text = ""
        for paragraph in self.doc.paragraphs:
            text += paragraph.text + "\n"
        return text

class DocumentErrorExporter:
    '''
    Generated by ChatGPT for writing DocumentError records to an Excel file
    '''
    def __init__(self, excel_file_path):
        self.excel_file_path = excel_file_path

    def export_to_excel(self,document_errors):
        data = []
        for error in document_errors:
            data.append({
                'Check Time': error.check_time,
                'Error Type': error.error_type,
                'Error Sub-Type': error.error_sub_type,
                'Error Message': error.error_msg,
                'Sentence': error.sentence,
                'From': error.char_position_in_text_from,
                'To': error.char_position_in_text_to,
                'Replacements': error.replacements
            })
        df = pd.DataFrame(data)
        df.to_excel(self.excel_file_path, sheet_name='Document Errors', index=False)

# Usage
if __name__ == "__main__":
    current_directory = os.getcwd()
    docx_file = current_directory+"/../../documents/user_1/Stakeholder_engagement.docx"
    docx_reader = DocxReader(docx_file)

    metadata = docx_reader.get_metadata()
    print("Metadata:")
    for key, value in metadata.items():
        print(f"{key}: {value}")

    text = docx_reader.get_text()
    print("\nText:")
    print(text)
